# Generated by Django 5.2.5 on 2025-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blogpost_cover_image_blogpost_cover_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("status", models.CharField(default="ok", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("tokens_prompt", models.IntegerField(blank=True, null=True)),
                ("tokens_completion", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source"], name="portfolio_k_source_4443d9_idx"
                    )
                ],
            },
        ),
    ]
