# Generated by Django 5.2.5 on 2025-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_chatlog_knowledgedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="answer_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
