# Generated by Django 5.2.6 on 2025-11-08 08:27

import django.db.models.deletion
import portfolio.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_profile_expansion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-published_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-start_date", "-end_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at", "title", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-level", "name", "id"]},
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=portfolio.storage_backends.SupabaseMediaStorage(),
                upload_to="blog/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=portfolio.storage_backends.SupabaseMediaStorage(),
                upload_to="profile/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=portfolio.storage_backends.SupabaseMediaStorage(),
                upload_to="projects/",
            ),
        ),
    ]
