# Generated by Django 5.2.6 on 2025-11-08 10:54

import portfolio.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_experience_rich_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=portfolio.storage_backends.SupabaseMediaStorage(),
                upload_to="experience/",
            ),
        ),
    ]
