# Generated by Django 5.2.6 on 2025-11-08 11:21

import django.db.models.deletion
import portfolio.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_experience_company_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.SmallIntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=portfolio.storage_backends.SupabaseMediaStorage(),
                        upload_to="blog/series/",
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["order", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="BlogSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("verify_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("unsub_token", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="bookmarks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="canonical_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_format",
            field=models.CharField(blank=True, default="markdown", max_length=20),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="pinned_order",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="seo_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="seo_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                blank=True,
                default="published",
                help_text="draft|published|archived",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="table_of_contents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField()),
                ("rendered_html", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="portfolio.blogcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portfolio.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.blogseries",
            ),
        ),
        migrations.CreateModel(
            name="BlogBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="portfolio.blogpost",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "fingerprint"),
                        name="unique_bookmark_per_fingerprint",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="portfolio.blogpost",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "fingerprint"),
                        name="unique_like_per_fingerprint",
                    )
                ],
            },
        ),
    ]
