# Generated by Django 5.2.6 on 2025-11-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0012_blogseries_blogsubscription_blogpost_allow_comments_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
